name: ci

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      target:
        description: "Nix build target"
        required: true
        default: "mk-out-archive-xcframeworks-macos-universal-video-default"

jobs:
  ci:
    name: ci
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            sandbox = true
            sandbox-fallback = false

      - name: Nix version
        run: nix --version

      - name: Show Nix config
        run: nix config show

      - name: Xcode version
        run: /Applications/Xcode_16.1.0.app/Contents/Developer/usr/bin/xcodebuild -version

      # See ${workspace}/nix/overlays/xcode.md
      - name: Set up Xcode in Nix store
        run: |
          XCODE_APP=$(realpath /Applications/Xcode_16.1.0.app)
          NIX_STORE_PATH="/nix/store/v92p4w6nxhyhq6lv0maq5cbb59mbxw5b-Xcode.app"
          HASH="sha256:d63c91255c8e98603b7f1470067c5225ab673850eed35449f5a0105c936e581c"

          sudo cp -a $XCODE_APP $NIX_STORE_PATH
          sudo sqlite3 /nix/var/nix/db/db.sqlite "INSERT INTO ValidPaths (path,hash,registrationTime) VALUES ('$NIX_STORE_PATH','$HASH',$(date +%s))"

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Determine version
        id: version
        run: |
          case "${GITHUB_REF}" in
          refs/tags/*)
            VERSION=${GITHUB_REF#refs/tags/}
            ;;
          *)
            VERSION=develop
            ;;
          esac

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo ${VERSION}

      - name: Build selected target
        id: build
        env:
          BUILD_TARGET: ${{ inputs.target || 'mk-out-archive-xcframeworks-macos-universal-video-default' }}
        run: |
          VERSION=${{ steps.version.outputs.version }}
          TARGET="$BUILD_TARGET"
          echo \"$VERSION\" > nix/utils/default/version.nix
          echo "target=${TARGET}" >> $GITHUB_OUTPUT
          nix build -v ".#${TARGET}" --out-link result-target

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.target }}
          if-no-files-found: error
          path: result-target/*.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: result-target/*.zip
